import type { Metadata } from 'next';
import { Doc } from '@/components/Doc';
import { APP_NAME } from '@/lib/brand';

export const metadata: Metadata = { title: `Terms: ${APP_NAME}` };

export default function Terms() {
  return (
    <Doc title="Terms">
      <p>By using {APP_NAME} you agree to these terms. {APP_NAME} is in early access.</p>
      <h2>Using the service</h2>
      <ul>
        <li>You need a Google account to sign in. You are responsible for what you create and for keeping your account secure.</li>
        <li>Do not use the service to make unlawful content, to attack or overload it, or to get around its limits.</li>
        <li>Monthly generation limits apply and may change.</li>
      </ul>
      <h2>Your content and AI output</h2>
      <p>You keep the rights you have in what you put in. Designs are generated by an AI model, so they can be wrong, similar to existing work, or unsuitable. Check them before you use them.</p>
      <h2>Early access</h2>
      <p>The service is provided as is, may change or stop, and may have errors. Pricing will be announced before any charge. To the extent the law allows, we are not liable for losses from using it.</p>
      <h2>Ending</h2>
      <p>You can delete your account at any time on the Account page. We may suspend accounts that break these terms.</p>
      <h2>Contact</h2>
      <p>[add a contact email before launch]</p>
    </Doc>
  );
}
